export {default as Signin } from './Auth/SignIn';
export {default as Dashboard} from './Dashboard';
export {default as Reservations } from './Reservations/Reservations';
export {default as AddReservations} from './Reservations/AddReservations';
export {default as UpdateReservations} from './Reservations/UpdateReservations';
export {default as Location} from './Location/Location';
export {default as AddLocation} from './Location/AddLocation';
export {default as UpdateLocattion} from './Location/UpdateLocation';
export {default as Cabins } from './Cabins/Cabins';
export {default as AddCabins } from './Cabins/AddCabins';
export {default as UpdateCabins } from './Cabins/UpdateCabins';
export {default as Staff} from './Staff/Staff';
export {default as AddStaff} from './Staff/AddStaff';
export {default as UpdateStaff} from './Staff/UpdateStaff';
export {default as Analytics} from './Analytics';
export {default as Feedback} from './Feedback';
export {default as SeasonalRule} from './PriceOptions/SeasonalRule';
export {default as AddSeasonalRule} from './PriceOptions/AddSeasonalRule';
export {default as UpdateSeasonalRule} from './PriceOptions/UpdateSeasonalRule';
export {default as ExtraCharge} from './PriceOptions/ExtraCharge';
export {default as AddExtraCharge} from './PriceOptions/AddExtraCharge';
export {default as UpdateExtraCharge} from './PriceOptions/UpdateExtraCharge';
export {default as Packages} from './PriceOptions/Packages';
export {default as CreatePackage} from './PriceOptions/CreatePackage';
export {default as GeneralSettings} from './Settings/GeneralSettings';
export {default as Emails} from './Settings/Emails';
export {default as Extras} from './Settings/Extras';
export {default as Policies} from './Settings/Policies';

